### ISSUE TITLE
请问下这个是多GPU训练的吗

### ISSUE THREAD

**Issue by yangyin2016** [Bil369/MaskDetect-YOLOv4-PyTorch#2]

**Comment by Bil369** [comment]
不是，这个是单卡训练。

**Comment by yangyin2016** [comment]
> 不是，这个是单卡训练。

 if Cuda:
        net = torch.nn.DataParallel(model)
        cudnn.benchmark = True
        net = net.cuda()
这块看着是并行

**Comment by Bil369** [comment]
> 不是，这个是单卡训练。
> 
> if Cuda:
> net = torch.nn.DataParallel(model)
> cudnn.benchmark = True
> net = net.cuda()
> 这块看着是并行

嗯，但是我只在单卡上进行了训练和测试，如果采用多卡的话可能需要仔细调整代码，保证多卡的负载均衡和避免BUG。

**Comment by yangyin2016** [comment]
> > 不是，这个是单卡训练。
> > if Cuda:
> > net = torch.nn.DataParallel(model)
> > cudnn.benchmark = True
> > net = net.cuda()
> > 这块看着是并行
> 
> 嗯，但是我只在单卡上进行了训练和测试，如果采用多卡的话可能需要仔细调整代码，保证多卡的负载均衡和避免BUG。

好的，谢谢~
